# Generated by Django 2.1.7 on 2019-04-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_contests_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contests',
            name='Website',
            field=models.CharField(default='DEFAULT VALUE', max_length=200),
        ),
        migrations.AlterField(
            model_name='contests',
            name='contestname',
            field=models.CharField(default='DEFAULT VALUE', max_length=200),
        ),
        migrations.AlterField(
            model_name='contests',
            name='date',
            field=models.CharField(default='DEFAULT VALUE', max_length=200),
        ),
        migrations.AlterField(
            model_name='contests',
            name='time',
            field=models.CharField(default='DEFAULT VALUE', max_length=200),
        ),
    ]
